### ISSUE TITLE
 Attempt to invoke interface method 'void microsoft.aspnet.signalr.client.Action.run(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by wallaceturner** [SignalR/java-client#113]
I'm getting the following error occasionally:

`2016-11-22 15:31:45.277:  - signalr error: 
java.lang.NullPointerException: Attempt to invoke interface method 'void microsoft.aspnet.signalr.client.Action.run(java.lang.Object)' on a null object reference
	at microsoft.aspnet.signalr.client.hubs.HubConnection.onReceived(HubConnection.java:92)
	at microsoft.aspnet.signalr.client.transport.TransportHelper.processReceivedData(TransportHelper.java:53)
	at microsoft.aspnet.signalr.client.Connection.processReceivedData(Connection.java:739)
	at microsoft.aspnet.signalr.client.Connection.access$000(Connection.java:30)
	at microsoft.aspnet.signalr.client.Connection$1.onData(Connection.java:303)
	at microsoft.aspnet.signalr.client.transport.HttpClientTransport$2.onResponse(HttpClientTransport.java:122)
	at microsoft.aspnet.signalr.client.http.java.NetworkRunnable.run(NetworkRunnable.java:82)
	at java.lang.Thread.run(Thread.java:818)`

It occurs when I send two (or more) requests via signalr that result in at least the same amount of callbacks. its not 100% reproducible but occurs often enough.

Interestingly the code in `HubConnection` where the error occurs does:

```
if (mCallbacks.containsKey(id)) {
        log("Get and remove callback with id: " + id, LogLevel.Verbose);
        Action<HubResult> callback = mCallbacks.remove(id);
    
        try {
            log("Execute callback for message", LogLevel.Verbose);
            callback.run(result);
        } catch (Exception e) {
            onError(e, false);
        }
    }
```

Could you instead replace the `containsKey` and `remove` call with a single `remove` call ? i.e.

```
    Action<HubResult> callback = mCallbacks.remove(id);
    if (callback!=null) {
         log("Get and remove callback with id: " + id, LogLevel.Verbose);
    try {
        log("Execute callback for message", LogLevel.Verbose);
        callback.run(result);
    } catch (Exception e) {
        onError(e, false);
    }
```

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
