### ISSUE TITLE
android 4 connection issue

### ISSUE THREAD

**Issue by fariz-siracli** [SignalR/java-client#132]
hi guys. I have just tried android client. It works with devices having android 5 and later, but for android 4 it gives following error. I tried on several devices and even in emulator. How to fix this. 
Thank you.
```
W/System.err: java.util.concurrent.ExecutionException: java.net.UnknownHostException: http://extra_api.gomap.az:88/signalr/negotiate?clientProtocol=1.3&connectionData=%5B%7B%22name%22%3A%22chathub%22%7D%5D
11-06 17:31:42.404 12211-12211/com.example.simplesignalrclient W/System.err:     at microsoft.aspnet.signalr.client.SignalRFuture.get(SignalRFuture.java:112)
11-06 17:31:42.404 12211-12211/com.example.simplesignalrclient W/System.err:     at microsoft.aspnet.signalr.client.SignalRFuture.get(SignalRFuture.java:102)
11-06 17:31:42.414 12211-12211/com.example.simplesignalrclient W/System.err:     at com.example.simplesignalrclient.SignalRService.startSignalR(SignalRService.java:109)
11-06 17:31:42.414 12211-12211/com.example.simplesignalrclient W/System.err:     at com.example.simplesignalrclient.SignalRService.onBind(SignalRService.java:67)
11-06 17:31:42.414 12211-12211/com.example.simplesignalrclient W/System.err:     at android.app.ActivityThread.handleBindService(ActivityThread.java:2653)
11-06 17:31:42.414 12211-12211/com.example.simplesignalrclient W/System.err:     at android.app.ActivityThread.access$1700(ActivityThread.java:149)
11-06 17:31:42.414 12211-12211/com.example.simplesignalrclient W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)
11-06 17:31:42.414 12211-12211/com.example.simplesignalrclient W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
11-06 17:31:42.414 12211-12211/com.example.simplesignalrclient W/System.err:     at android.os.Looper.loop(Looper.java:137)
11-06 17:31:42.414 12211-12211/com.example.simplesignalrclient W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5214)
11-06 17:31:42.414 12211-12211/com.example.simplesignalrclient W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
11-06 17:31:42.414 12211-12211/com.example.simplesignalrclient W/System.err:     at java.lang.reflect.Method.invoke(Method.java:525)
11-06 17:31:42.414 12211-12211/com.example.simplesignalrclient W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
11-06 17:31:42.414 12211-12211/com.example.simplesignalrclient W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
11-06 17:31:42.414 12211-12211/com.example.simplesignalrclient W/System.err:     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
