### ISSUE TITLE
Deadlock

### ISSUE THREAD

**Issue by andre77** [SignalR/java-client#133]
From time to time it looks, like we have a deadlock, the whole application needs to be restarted. Here a couple of stacktraces from the jstack dump:

`
"Thread-33952": waiting to acquire [0x00000006f7784038], holding [0x00000006f7783fa0, 0x00000006f7782978, 0x00000006f77829a0, 0x00000006f77829c8]
"Thread-33952": waiting to acquire [0x00000006f7784038], holding [0x00000006f7783fa0, 0x00000006f7782978, 0x00000006f77829a0, 0x00000006f77829c8]
	at microsoft.aspnet.signalr.client.Connection$6.run(Connection.java:483)
	at microsoft.aspnet.signalr.client.SignalRFuture.cancel(SignalRFuture.java:53)
	at microsoft.aspnet.signalr.client.Connection.disconnect(Connection.java:538)
	at microsoft.aspnet.signalr.client.Connection.onError(Connection.java:772)
	at microsoft.aspnet.signalr.client.Connection$2.onError(Connection.java:325)
	at microsoft.aspnet.signalr.client.SignalRFuture.triggerError(SignalRFuture.java:185)
	at microsoft.aspnet.signalr.client.Connection$4.onError(Connection.java:380)
	at microsoft.aspnet.signalr.client.SignalRFuture.triggerError(SignalRFuture.java:185)
	at microsoft.aspnet.signalr.client.FutureHelper$2.onError(FutureHelper.java:38)
	at microsoft.aspnet.signalr.client.SignalRFuture.triggerError(SignalRFuture.java:185)
	at microsoft.aspnet.signalr.client.http.java.NetworkRunnable.run(NetworkRunnable.java:93)
	at java.lang.Thread.run(Thread.java:748)
"Thread-33953": waiting to acquire [0x00000006f7783fa0], holding [0x00000006f7784038, 0x00000006f7784080]
"Thread-33953": waiting to acquire [0x00000006f7783fa0], holding [0x00000006f7784038, 0x00000006f7784080]
	at microsoft.aspnet.signalr.client.Connection.disconnect(Connection.java:505)
	at microsoft.aspnet.signalr.client.Connection$5.onError(Connection.java:472)
	at microsoft.aspnet.signalr.client.SignalRFuture.triggerError(SignalRFuture.java:185)
	at microsoft.aspnet.signalr.client.http.java.NetworkRunnable.run(NetworkRunnable.java:93)
	at java.lang.Thread.run(Thread.java:748)

...

Found one Java-level deadlock:
=============================
"Thread-33953":
  waiting to lock monitor 0x00007f61e0297058 (object 0x00000006f7783fa0, a java.lang.Object),
  which is held by "Thread-33952"
"Thread-33952":
  waiting to lock monitor 0x00007f61b0072638 (object 0x00000006f7784038, a java.lang.Object),
  which is held by "Thread-33953"

Java stack information for the threads listed above:
===================================================
"Thread-33953":
	at microsoft.aspnet.signalr.client.Connection.disconnect(Connection.java:505)
	- waiting to lock <0x00000006f7783fa0> (a java.lang.Object)
	at microsoft.aspnet.signalr.client.Connection$5.onError(Connection.java:472)
	- locked <0x00000006f7784038> (a java.lang.Object)
	at microsoft.aspnet.signalr.client.SignalRFuture.triggerError(SignalRFuture.java:185)
	- locked <0x00000006f7784080> (a java.lang.Object)
	at microsoft.aspnet.signalr.client.http.java.NetworkRunnable.run(NetworkRunnable.java:93)
	at java.lang.Thread.run(Thread.java:748)
"Thread-33952":
	at microsoft.aspnet.signalr.client.Connection$6.run(Connection.java:483)
	- waiting to lock <0x00000006f7784038> (a java.lang.Object)
	at microsoft.aspnet.signalr.client.SignalRFuture.cancel(SignalRFuture.java:53)
	at microsoft.aspnet.signalr.client.Connection.disconnect(Connection.java:538)
	- locked <0x00000006f7783fa0> (a java.lang.Object)
	at microsoft.aspnet.signalr.client.Connection.onError(Connection.java:772)
	at microsoft.aspnet.signalr.client.Connection$2.onError(Connection.java:325)
	at microsoft.aspnet.signalr.client.SignalRFuture.triggerError(SignalRFuture.java:185)
	- locked <0x00000006f7782978> (a java.lang.Object)
	at microsoft.aspnet.signalr.client.Connection$4.onError(Connection.java:380)
	at microsoft.aspnet.signalr.client.SignalRFuture.triggerError(SignalRFuture.java:185)
	- locked <0x00000006f77829a0> (a java.lang.Object)
	at microsoft.aspnet.signalr.client.FutureHelper$2.onError(FutureHelper.java:38)
	at microsoft.aspnet.signalr.client.SignalRFuture.triggerError(SignalRFuture.java:185)
	- locked <0x00000006f77829c8> (a java.lang.Object)
	at microsoft.aspnet.signalr.client.http.java.NetworkRunnable.run(NetworkRunnable.java:93)
	at java.lang.Thread.run(Thread.java:748)

Found 1 deadlock.
`

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
