### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by muhammad-naderi** [SignalR/java-client#143]
When application is open and network connection losses, app will crash with following stacktrace:
```

java.lang.NullPointerException: Attempt to invoke virtual method 'void microsoft.aspnet.signalr.client.HeartbeatMonitor.stop()' on a null object reference
        at microsoft.aspnet.signalr.client.Connection.reconnect(Connection.java:795)
        at microsoft.aspnet.signalr.client.Connection.onError(Connection.java:765)
        at microsoft.aspnet.signalr.client.Connection$2.onError(Connection.java:325)
        at microsoft.aspnet.signalr.client.SignalRFuture.triggerError(SignalRFuture.java:185)
        at microsoft.aspnet.signalr.client.Connection$4.onError(Connection.java:380)
        at microsoft.aspnet.signalr.client.SignalRFuture.triggerError(SignalRFuture.java:185)
        at microsoft.aspnet.signalr.client.FutureHelper$2.onError(FutureHelper.java:38)
        at microsoft.aspnet.signalr.client.SignalRFuture.triggerError(SignalRFuture.java:185)
        at microsoft.aspnet.signalr.client.http.java.NetworkRunnable.run(NetworkRunnable.java:92)
        at java.lang.Thread.run(Thread.java:818)

```

this also happens if server gets restarted or AppPool gets Recycled

**Comment by luimi** [comment]
+1 , but this is not allways, just some times

**Comment by muhammad-naderi** [comment]
I get it a lot, so what I did is to use UncaughtExceptionHandler in my app, and some dirty works there, I mean if I find that the uncaught exception is from the almighty Microsoft package! I just catch it, an re instantiate my signalR module ,

this is clearly not a good approach, but since the whole team was busy enough for the last 4 years to maintain the library, for now it is the only thing we can do

**Comment by quensh93** [comment]
i have the same problem too, but it usually happen when application is in onpause state and attempting to reconnect to server

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
