### ISSUE TITLE
NullPointerExcepetion --> SignalR Android Service

### ISSUE THREAD

**Issue by renangrativol** [SignalR/java-client#24]
I´m running signalR as a Service (Android) and the error below occur very often:

java.lang.NullPointerException
            at microsoft.aspnet.signalr.client.Connection.reconnect(Connection.java:795)
            at microsoft.aspnet.signalr.client.Connection.onError(Connection.java:765)
            at microsoft.aspnet.signalr.client.Connection$2.onError(Connection.java:325)
            at microsoft.aspnet.signalr.client.SignalRFuture.triggerError(SignalRFuture.java:185)
            at microsoft.aspnet.signalr.client.transport.AutomaticTransport$2.onError(AutomaticTransport.java:107)
            at microsoft.aspnet.signalr.client.SignalRFuture.triggerError(SignalRFuture.java:185)
            at microsoft.aspnet.signalr.client.http.java.NetworkRunnable.run(NetworkRunnable.java:92)
            at java.lang.Thread.run(Thread.java:841)

Could you help me, please?

Thank you!

**Comment by prateekdroid08** [comment]
Hey renangrativol

I am facing same issue but not able to track what is my fault.

Please suggest

**Comment by nicknabdullah** [comment]
Hi @renangrativol 
Getting this issue quite often.
Can you please share how you resolved it.

**Comment by rgrativol** [comment]
Sorry guys, I don´t remember what I did. It was a long time ago.

**Comment by nicknabdullah** [comment]
Hi @prateekdroid08 
Were you able to solve this? I'm facing the same problem...
