### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by Gex8** [SignalR/java-client#29]
Dear Developers,

We have some problem in our android application, the app crash with the following stacktrace:

```
java.util.ConcurrentModificationException
       at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
       at microsoft.aspnet.signalr.client.SignalRFuture.cancel(SignalRFuture.java:52)
       at microsoft.aspnet.signalr.client.UpdateableCancellableFuture.cancel(UpdateableCancellableFuture.java:39)
       at microsoft.aspnet.signalr.client.Connection.disconnect(Connection.java:532)
       at microsoft.aspnet.signalr.client.Connection.onError(Connection.java:768)
       at microsoft.aspnet.signalr.client.Connection$2.onError(Connection.java:325)
       at microsoft.aspnet.signalr.client.SignalRFuture.triggerError(SignalRFuture.java:185)
       at microsoft.aspnet.signalr.client.transport.AutomaticTransport$2.onError(AutomaticTransport.java:116)
       at microsoft.aspnet.signalr.client.SignalRFuture.triggerError(SignalRFuture.java:185)
       at microsoft.aspnet.signalr.client.transport.LongPollingTransport$3.onError(LongPollingTransport.java:149)
       at microsoft.aspnet.signalr.client.SignalRFuture.triggerError(SignalRFuture.java:185)
       at microsoft.aspnet.signalr.client.http.java.NetworkRunnable.run(NetworkRunnable.java:92)
       at java.lang.Thread.run(Thread.java:841)
```

As you see, this issue is coming from the signalR library. Please let me know how can we avoid the problem, or if you can fix it, we would be happy.

Yours Sincerely,
Gergo

**Comment by peplamb** [comment]
I am receiving similar issue,

    java.util.ConcurrentModificationException
            at java.util.HashMap$HashIterator.nextEntry(HashMap.java:806)
            at java.util.HashMap$KeyIterator.next(HashMap.java:833)
            at microsoft.aspnet.signalr.client.hubs.HubConnection.clearInvocationCallbacks(HubConnection.java:172)
            at microsoft.aspnet.signalr.client.hubs.HubConnection.onClosed(HubConnection.java:163)
            at microsoft.aspnet.signalr.client.Connection.disconnect(Connection.java:550)
            at microsoft.aspnet.signalr.client.Connection.onError(Connection.java:769)
            at microsoft.aspnet.signalr.client.Connection$2.onError(Connection.java:326)
            at microsoft.aspnet.signalr.client.SignalRFuture.triggerError(SignalRFuture.java:185)
            at microsoft.aspnet.signalr.client.Connection$4.onError(Connection.java:381)
            at microsoft.aspnet.signalr.client.SignalRFuture.triggerError(SignalRFuture.java:185)
            at microsoft.aspnet.signalr.client.FutureHelper$2.onError(FutureHelper.java:38)
            at microsoft.aspnet.signalr.client.SignalRFuture.triggerError(SignalRFuture.java:185)
            at microsoft.aspnet.signalr.client.http.java.NetworkRunnable.run(NetworkRunnable.java:92)
            at java.lang.Thread.run(Thread.java:841)

**Comment by arnoldpistorius** [comment]
@peplamb I had this issue too, I wrote a fix which is merged by @PabloZaiden. Do you have the latest version?

**Comment by peplamb** [comment]
Thank you @arnoldpistorius 

Folloing is the issue when upgraded to the latest version. After "ConnectionState.Connecting" the ConnectionState is always going to "ConnectionState.Disconnected" this was not happening before.

Following is my code in Android,

     connection.stateChanged(new StateChangedCallback() {
            @Override
            public void stateChanged(ConnectionState oldState, ConnectionState newState) {
                if (newState == ConnectionState.Connecting) {
                    //Loog.send(TAG, "connecting...");
                }
                else if (newState == ConnectionState.Reconnecting) {
                    //Loog.send(TAG, "re-connecting...");
                }
                else if (newState == ConnectionState.Disconnected) {
                    //Loog.send(TAG, "disconnected.");
                    Thread thread = new Thread() {
                        @Override
                        public void run() {
                            try {
                                SystemClock.sleep(5000); // Re-connect after "5" seconds.
                                connect();
                            } catch (Exception e) {
                                //Loog.send(TAG, e.getMessage());
                            }
                        }
                    };
                    thread.start();
                }
                else if (newState == ConnectionState.Connected) {
                    //Loog.send(TAG, "connected.");
                }
            }
        });

It works fine with 'java-client-56a2e05afeb05baf5c36b2646c2e4b7c9d52c220' but keeps reconnecting with java-client-master

If i downgrade I have the above mentioned issue.

**Comment by hemanthme** [comment]
Any fix for this issue??

**Comment by MinChanSike** [comment]
I think, you have to provide Credentials to connection.
In SignalR Java-client can use CookieCredentials and BasicAuthenticationCredentials.

**Comment by hemanthme** [comment]
yeah this seems to temporarily fix the issue of reconnecting.. but sometimes i still get the ConcurrentModificationException. usually when the App went to offline.

**Comment by bojancv** [comment]
I am also experiencing this issue only on Android 5.1.1 ?

**Comment by a6datta** [comment]
@hemanthme Did you manage to resolve the ConcurrentModificationException. This project looks dead. I am planning to implement an alternative solution. However in the mean time I was looking for a workaround. I would be grateful to you if you could share your solution. How do you provide Credentials to connection?

**Comment by hemanthme** [comment]
No this issue happens occasionally... i cannot share the code as i dont have access to it anymore. sorry..

**Comment by SaadBilal** [comment]
@PabloZaiden, can you help regarding this issue. @peplamb wrote a fix, can you guys help on this issue

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
