### ISSUE TITLE
ArrayIndexOutOfBoundsException causes disconnect

### ISSUE THREAD

**Issue by arnoldpistorius** [SignalR/java-client#58]
The following exception occurs at random. I can see in the trace that this has something to do with data which is coming in from the server, but got corrupt during the transfer. When this happens, the connection gets closed immediately.

The environment is an Android phone (Nexus 5) with Lollipop 5.0.1 and the latest version of the SignalR java-client.

I got the following exception from the error callback event:

```
01-15 14:29:54.111   9835-11514/com.mycompany.app E/wsp-signalr﹕ java.lang.ArrayIndexOutOfBoundsException
            at com.android.okio.Util.checkOffsetAndCount(Util.java:29)
            at com.android.okio.OkBuffer.skip(OkBuffer.java:391)
            at com.android.okio.OkBuffer.readUtf8Line(OkBuffer.java:331)
            at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:96)
            at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.readChunkSize(HttpConnection.java:510)
            at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.read(HttpConnection.java:491)
            at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
            at java.io.InputStreamReader.read(InputStreamReader.java:231)
            at java.io.BufferedReader.fillBuf(BufferedReader.java:145)
            at java.io.BufferedReader.readLine(BufferedReader.java:397)
            at microsoft.aspnet.signalr.client.http.StreamResponse.readToEnd(StreamResponse.java:72)
            at microsoft.aspnet.signalr.client.transport.LongPollingTransport$1.onResponse(LongPollingTransport.java:107)
            at microsoft.aspnet.signalr.client.http.java.NetworkRunnable.run(NetworkRunnable.java:82)
            at java.lang.Thread.run(Thread.java:818)
01-15 14:29:54.187   9835-11517/com.mycompany.app E/wsp-signalr﹕ java.lang.Exception: Connection closed
            at microsoft.aspnet.signalr.client.hubs.HubProxy$2.run(HubProxy.java:229)
            at microsoft.aspnet.signalr.client.hubs.HubProxy$2.run(HubProxy.java:219)
            at microsoft.aspnet.signalr.client.hubs.HubConnection.clearInvocationCallbacks(HubConnection.java:175)
            at microsoft.aspnet.signalr.client.hubs.HubConnection.onClosed(HubConnection.java:163)
            at microsoft.aspnet.signalr.client.Connection.disconnect(Connection.java:550)
            at microsoft.aspnet.signalr.client.Connection$7.run(Connection.java:496)
            at microsoft.aspnet.signalr.client.Connection$7.run(Connection.java:490)
            at microsoft.aspnet.signalr.client.SignalRFuture.setResult(SignalRFuture.java:73)
            at microsoft.aspnet.signalr.client.http.java.NetworkRunnable.run(NetworkRunnable.java:83)
            at java.lang.Thread.run(Thread.java:818)
01-15 14:29:54.187   9835-11517/com.mycompany.app E/wsp-signalr﹕ java.lang.Exception: Connection closed
            at microsoft.aspnet.signalr.client.hubs.HubProxy$2.run(HubProxy.java:229)
            at microsoft.aspnet.signalr.client.hubs.HubProxy$2.run(HubProxy.java:219)
            at microsoft.aspnet.signalr.client.hubs.HubConnection.clearInvocationCallbacks(HubConnection.java:175)
            at microsoft.aspnet.signalr.client.hubs.HubConnection.onClosed(HubConnection.java:163)
            at microsoft.aspnet.signalr.client.Connection.disconnect(Connection.java:550)
            at microsoft.aspnet.signalr.client.Connection$7.run(Connection.java:496)
            at microsoft.aspnet.signalr.client.Connection$7.run(Connection.java:490)
            at microsoft.aspnet.signalr.client.SignalRFuture.setResult(SignalRFuture.java:73)
            at microsoft.aspnet.signalr.client.http.java.NetworkRunnable.run(NetworkRunnable.java:83)
            at java.lang.Thread.run(Thread.java:818)
01-15 14:29:54.188   9835-11517/com.mycompany.app E/wsp-signalr﹕ java.lang.Exception: Connection closed
            at microsoft.aspnet.signalr.client.hubs.HubProxy$2.run(HubProxy.java:229)
            at microsoft.aspnet.signalr.client.hubs.HubProxy$2.run(HubProxy.java:219)
            at microsoft.aspnet.signalr.client.hubs.HubConnection.clearInvocationCallbacks(HubConnection.java:175)
            at microsoft.aspnet.signalr.client.hubs.HubConnection.onClosed(HubConnection.java:163)
            at microsoft.aspnet.signalr.client.Connection.disconnect(Connection.java:550)
            at microsoft.aspnet.signalr.client.Connection$7.run(Connection.java:496)
            at microsoft.aspnet.signalr.client.Connection$7.run(Connection.java:490)
            at microsoft.aspnet.signalr.client.SignalRFuture.setResult(SignalRFuture.java:73)
            at microsoft.aspnet.signalr.client.http.java.NetworkRunnable.run(NetworkRunnable.java:83)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by arnoldpistorius** [comment]
This is still an issue... Tried updated my Gson library, but this doesn't make a difference.

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
