### ISSUE TITLE
Fail parse DateTime without DateTimeOffset

### ISSUE THREAD

**Issue by yyjdelete** [SignalR/java-client#69]
The orig data is "2015-02-06T19:58:00.277"

com.google.gson.JsonParseException: java.text.ParseException: Unparseable date: "2015-02-06T19:58:00000000.77" (at offset 28)
            at microsoft.aspnet.signalr.client.DateSerializer.deserialize(DateSerializer.java:41)
            at microsoft.aspnet.signalr.client.DateSerializer.deserialize(DateSerializer.java:27)
            at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
            at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
            at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
            at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
            at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
            at com.google.gson.Gson.fromJson(Gson.java:810)
            at com.google.gson.Gson.fromJson(Gson.java:875)
            at com.google.gson.Gson.fromJson(Gson.java:848)
            at microsoft.aspnet.signalr.client.hubs.HubProxy$1.run(HubProxy.java:155)
            at microsoft.aspnet.signalr.client.hubs.HubProxy$1.run(HubProxy.java:141)
            at microsoft.aspnet.signalr.client.hubs.Subscription.onReceived(Subscription.java:31)
            at microsoft.aspnet.signalr.client.hubs.HubProxy.invokeEvent(HubProxy.java:413)
            at microsoft.aspnet.signalr.client.hubs.HubConnection.onReceived(HubConnection.java:118)
            at microsoft.aspnet.signalr.client.transport.TransportHelper.processReceivedData(TransportHelper.java:96)
            at microsoft.aspnet.signalr.client.Connection.processReceivedData(Connection.java:739)
            at microsoft.aspnet.signalr.client.Connection.access$000(Connection.java:30)
            at microsoft.aspnet.signalr.client.Connection$10.onData(Connection.java:677)
            at microsoft.aspnet.signalr.client.transport.LongPollingTransport$1.onResponse(LongPollingTransport.java:113)
            at microsoft.aspnet.signalr.client.http.java.NetworkRunnable.run(NetworkRunnable.java:82)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: java.text.ParseException: Unparseable date: "2015-02-06T19:58:00000000.77" (at offset 28)
            at java.text.DateFormat.parse(DateFormat.java:555)
            at microsoft.aspnet.signalr.client.DateSerializer.deserialize(DateSerializer.java:104)
            at microsoft.aspnet.signalr.client.DateSerializer.deserialize(DateSerializer.java:39)
            at microsoft.aspnet.signalr.client.DateSerializer.deserialize(DateSerializer.java:27)
            at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
            at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
            at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
            at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
            at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
            at com.google.gson.Gson.fromJson(Gson.java:810)
            at com.google.gson.Gson.fromJson(Gson.java:875)
            at com.google.gson.Gson.fromJson(Gson.java:848)
            at microsoft.aspnet.signalr.client.hubs.HubProxy$1.run(HubProxy.java:155)
            at microsoft.aspnet.signalr.client.hubs.HubProxy$1.run(HubProxy.java:141)
            at microsoft.aspnet.signalr.client.hubs.Subscription.onReceived(Subscription.java:31)
            at microsoft.aspnet.signalr.client.hubs.HubProxy.invokeEvent(HubProxy.java:413)
            at microsoft.aspnet.signalr.client.hubs.HubConnection.onReceived(HubConnection.java:118)
            at microsoft.aspnet.signalr.client.transport.TransportHelper.processReceivedData(TransportHelper.java:96)
            at microsoft.aspnet.signalr.client.Connection.processReceivedData(Connection.java:739)
            at microsoft.aspnet.signalr.client.Connection.access$000(Connection.java:30)
            at microsoft.aspnet.signalr.client.Connection$10.onData(Connection.java:677)
            at microsoft.aspnet.signalr.client.transport.LongPollingTransport$1.onResponse(LongPollingTransport.java:113)
            at microsoft.aspnet.signalr.client.http.java.NetworkRunnable.run(NetworkRunnable.java:82)
            at java.lang.Thread.run(Thread.java:841)

**Comment by yyjdelete** [comment]
I'm not sure why there is not an "Z" at the end, but maybe I will create an PR to fix it.
Microsoft.AspNet.SignalR.2.2.0 & EntityFramework.6.1.2 is used.


Full test.
Input | Output | Result
------------ | ------------- | -------------
2015-02-06T19:58:00.277 | 2015-02-06T19:58:00000000.77 | FAILED
2015-02-06T19:58:00.27 | 2015-02-06T19:580000000:0027 | FAILED
2015-02-06T19:58:00.2 | 2015-02-06T19:5000000008:0.2 | FAILED
2015-02-06T19:58:00. | 2015-02-06T19:00000000058:0. | FAILED
2015-02-06T19:58:00 | 2015-02-06T19:58:00.000+0000 | SUCCESS
- | - | -
2015-02-06T19:58:00.277Z | 2015-02-06T19:58:00.277+0000 | FAILED
2015-02-06T19:58:00.27Z | 2015-02-06T19:58:00.27.+0000 | FAILED
2015-02-06T19:58:00.2Z | 2015-02-06T19:58:00.2.0+0000 | FAILED
2015-02-06T19:58:00.Z | 2015-02-06T19:58:00.000+0000 | SUCCESS
2015-02-06T19:58:00Z | 2015-02-06T19:58:00.000+0000 | SUCCESS
- | - | -
2015-02-06T19:58:00.277+00:00 | 2015-02-06T19:58:00000000.77 | FAILED
2015-02-06T19:58:00.27+00:00 | 2015-02-06T19:580000000:0027 | FAILED
2015-02-06T19:58:00.2+00:00 | 2015-02-06T19:5000000008:0.2 | FAILED
2015-02-06T19:58:00.+00:00 | 2015-02-06T19:00000000058:0. | FAILED
2015-02-06T19:58:00+00:00 | 2015-02-06T19:58:00.000+0000 | SUCCESS

**Comment by yyjdelete** [comment]
Maybe relate to issue #14

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
