### ISSUE TITLE
android studio compile error

### ISSUE THREAD

**Issue by spartacus777** [SignalR/java-client#84]
I compile project, in order to receive desired libs, and receive compilation error - 

`````` java
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
    at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
    at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
    at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
    at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
    at com.android.dx.command.dexer.Main.processClass(Main.java:704)
    at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
    at com.android.dx.command.dexer.Main.access$300(Main.java:83)
    at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
    at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
    at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
    at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
    at com.android.dx.command.dexer.Main.processOne(Main.java:632)
    at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
    at com.android.dx.command.dexer.Main.run(Main.java:246)
    at com.android.dx.command.dexer.Main.main(Main.java:215)
    at com.android.dx.command.Main.main(Main.java:106)
...while parsing microsoft/aspnet/signalr/client/Action.class
1 error; aborting
Error:Execution failed for task ':app:preDexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_45\bin\java.exe'' finished with non-zero exit value 1```

Please help me to build your project, we are gono use it in or social network. Any help really appreciated!
``````

**Comment by DevRollingStone** [comment]
This may be caused by mismatch Java version between your Android apps and SignalR libs.
For example you compiled SignalR libs in one environment with Java 1.7,
then you copy the compiled SignalR libs to your apps source with another environtment with Java 1.8, the error you mentioned may occur.
Use the "Source Compatability" or make sure you have the identical JRE between app and the lib.

**Comment by spartacus777** [comment]
In order to make signalR work on my project, I had to downgrade Java ver I use to Java1.7, really.
It works now, but i have got another fatal for me issue - https://github.com/SignalR/java-client/issues/85

**Comment by sattha** [comment]
Please see my question at...

https://stackoverflow.com/questions/33196087/gradle-compile-success-but-fail-to-run-project

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
