### ISSUE TITLE
Hub is returning HTML instead of JSON

### ISSUE THREAD

**Issue by a6datta** [SignalR/java-client#89]
I have signalr hub running in Asp.net web api. I can send and receive messages by calling hub and client functions from a dot net client. Now I am trying to implement the same on java client (Android platform). I managed to connect to the hub and receive the messages. However when I am sending message, it throws an exception. When sending messages (calling hub function), the hub function gets called successfully and the other side receives the message too. However the response (back to the sender) from the hub is in html format rather than json. That throws an exception on client side. I could ignore the exception for the time being as the messages are going through. However I am not able to catch the exception, as a result of this the android process gets terminated.

Client code:

    private HubConnection mConnection;
    private HubProxy mProxy;

        @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        initializeSignalr();
        connectNotificationHub();

        Button btnSend = (Button) findViewById(R.id.btnSend);
        View.OnClickListener oclBtnSend = new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                try {
                    mProxy.invoke("SendToOperators", "21", "test message", "chat").done(new Action<Void>() {
                        @Override
                        public void run(Void obj) throws Exception {
                            System.out.println("SENT!");
                        }
                    }).onError(new ErrorCallback() {
                        @Override
                        public void onError(Throwable throwable) {
                            System.out.println("ERROR!");
                        }
                    }).get();
                } catch (Exception e) {
                    
                } 
            }
        };
        btnSend.setOnClickListener(oclBtnSend);
    }

        public void initializeSignalr(){
        Platform.loadPlatformComponent(new AndroidPlatformComponent());
    }

    public void ShutdownSignalr(){
        if(mConnection!=null){
            //mConnection.disconnect();
            mConnection.stop();
            mConnection=null;
        }
    }

    public void connectNotificationHub()
    {
        String server = REST_SERVICE_URL+"signalr";
        mConnection = new HubConnection(server,"userName="+IMUSER_PFX+"_driver"+Integer.toString(DriverID),true, new Logger() {
            @Override
            public void log(String message, LogLevel level) {
                if (level == LogLevel.Critical) {
                Log.d("SIGNALR", level.toString() + ": " + message);
                }
            }
        });

        mProxy = mConnection.createHubProxy("NotificationHub");

        mProxy.subscribe(new Object() {
            @SuppressWarnings("unused")
            public void addMessage(String name, String message) {
                Log.d("Message: ", message);
            }
        });

        mConnection.error(new ErrorCallback() {
            @Override
            public void onError(Throwable error) {
                error.printStackTrace();
            }
        });

        SignalRFuture<Void> awaitConnection = mConnection.start();
        try {
            awaitConnection.get();
        } catch (InterruptedException e) {
            e.printStackTrace();
        } catch (ExecutionException e) {
            e.printStackTrace();
        }
    }

In dot net client it was not possible to catch exception with try catch clock if the server was not available however I was able to resolve it by subscribing to error callback 

    mConnection.error(new ErrorCallback() {
        @Override
        public void onError(Throwable error) {
            error.printStackTrace();
        }
    });

In java client when I am sending message

    try {
                mProxy.invoke("SendToOperators", "21", "test message", "chat").done(new Action<Void>() {
                    @Override
                    public void run(Void obj) throws Exception {
                        System.out.println("SENT!");
                    }
                }).onError(new ErrorCallback() {
                    @Override
                    public void onError(Throwable throwable) {
                        System.out.println("ERROR!");
                    }
                }).get();
            } catch (Exception e) {

            }

it throwing json parsing exception

    11-22 03:42:27.776  19661-20016/com.eb5.uvexa.uvexadriver D/SIGNALR﹕ Critical: HubConnection - Error: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected EOF at line 1 column 10
    11-22 03:42:27.786  19661-20016/com.eb5.uvexa.uvexadriver W/System.err﹕ com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected EOF at line 1 column 10
    11-22 03:42:27.786  19661-20016/com.eb5.uvexa.uvexadriver W/System.err﹕ at com.google.gson.JsonParser.parse(JsonParser.java:65)
    11-22 03:42:27.786  19661-20016/com.eb5.uvexa.uvexadriver W/System.err﹕ at com.google.gson.JsonParser.parse(JsonParser.java:45)
    11-22 03:42:27.786  19661-20016/com.eb5.uvexa.uvexadriver W/System.err﹕ at microsoft.aspnet.signalr.client.transport.TransportHelper.processReceivedData(TransportHelper.java:41)
    11-22 03:42:27.786  19661-20016/com.eb5.uvexa.uvexadriver W/System.err﹕ at microsoft.aspnet.signalr.client.Connection.processReceivedData(Connection.java:733)
    11-22 03:42:27.786  19661-20016/com.eb5.uvexa.uvexadriver W/System.err﹕ at microsoft.aspnet.signalr.client.Connection.access$0(Connection.java:728)
    11-22 03:42:27.786  19661-20016/com.eb5.uvexa.uvexadriver W/System.err﹕ at microsoft.aspnet.signalr.client.Connection$1.onData(Connection.java:302)
    11-22 03:42:27.786  19661-20016/com.eb5.uvexa.uvexadriver W/System.err﹕ at microsoft.aspnet.signalr.client.transport.HttpClientTransport$2.onResponse(HttpClientTransport.java:122)
    11-22 03:42:27.786  19661-20016/com.eb5.uvexa.uvexadriver W/System.err﹕ at microsoft.aspnet.signalr.client.http.java.NetworkRunnable.run(NetworkRunnable.java:82)
    11-22 03:42:27.786  19661-20016/com.eb5.uvexa.uvexadriver W/System.err﹕ at java.lang.Thread.run(Thread.java:864)
    11-22 03:42:27.786  19661-20016/com.eb5.uvexa.uvexadriver W/System.err﹕ Caused by: com.google.gson.stream.MalformedJsonException: Expected EOF at line 1 column 10
    11-22 03:42:27.786  19661-20016/com.eb5.uvexa.uvexadriver W/System.err﹕ at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1310)
    11-22 03:42:27.786  19661-20016/com.eb5.uvexa.uvexadriver W/System.err﹕ at com.google.gson.stream.JsonReader.peek(JsonReader.java:390)
    11-22 03:42:27.786  19661-20016/com.eb5.uvexa.uvexadriver W/System.err﹕ at com.google.gson.JsonParser.parse(JsonParser.java:60)
    11-22 03:42:27.786  19661-20016/com.eb5.uvexa.uvexadriver W/System.err﹕ ... 8 more

I am receiving the message on other side. But the response from the hub is in html format rather than json. I am sure it's a bug, which I will post on github signalr issue tracker. However I needed a way to stop the android client from crashing.

The html response from the hub

    11-22 03:42:27.766  19661-20016/com.eb5.uvexa.uvexadriver D/SIGNALR﹕ Verbose: serverSentEvents - Response received
    11-22 03:42:27.766  19661-20016/com.eb5.uvexa.uvexadriver D/SIGNALR﹕ Verbose: serverSentEvents - Read response to the end
    11-22 03:42:27.776  19661-20016/com.eb5.uvexa.uvexadriver D/SIGNALR﹕ Verbose: serverSentEvents - Trigger onData with data: {"I":"1"}<!DOCTYPE html>
    <html>
    <head>
    <title>Runtime Error</title>
    <meta name="viewport" content="width=device-width" />
    <style>
    body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;}
    p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
    b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
    H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
    H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
    pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
    .marker {font-weight: bold; color: black;text-decoration: none;}
    .version {color: gray;}
    .error {margin-bottom: 10px;}
    .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }
    @media screen and (max-width: 639px) {
    pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
    }
    @media screen and (max-width: 479px) {
    pre { width: 280px; }
    }
    </style>
    </head>
    <body bgcolor="white">
    <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>
    <h2> <i>Runtime Error</i> </h2></span>
    <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">
    <b> Description: </b>An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.
    <br><br>
    <b>Details:</b> To enable the details of this specific error message to be viewable on remote machines, please create a &lt;customErrors&gt; tag within a &quot;web.config&quot; configuration file located in the root directory of the current web application. This &lt;customErrors&gt; tag should then have its &quot;mode&quot; attribute set to &quot;Off&quot;.<br><br>
    <table width=100% bgcolor="#ffffcc">
    <tr>
    <td>
    <code><pre>
    &lt;!-- Web.Config Configuration File --&gt;
    &lt;configuration&gt;
    &lt;system.web&gt;
    &lt;customErrors mode=&quot;Off&quot;/&gt;
    &lt;/system.web&gt;
    &lt;/configuration&gt;</pre></code>
    </td>
    </tr>
    </table>
    <br>
    <b>Notes:</b> The current error page you are seeing can be replaced by a custom error page by modifying the &quot;defaultRedirect&quot; attribute of the application&#39;s &lt;customErrors&gt; configuration tag to point to a custom error page URL.<br><br>
    <table width=100% bgcolor="#ffffcc">
    <tr>
    <td>
    <code><pre>
    &lt;!-- Web.Config Configuration File --&gt;
    &lt;configuration&gt;
    &lt;system.web&gt;
    &lt;customErrors mode=&quot;RemoteOnly&quot; defaultRedirect=&quot;mycustompage.htm&quot;/&gt;
    &lt;/system.web&gt;
    &lt;/configuration&gt;</pre></code>
    </td>
    </tr>
    </table>
    <br>
    </body>
    </html>

**Comment by a6datta** [comment]
I managed to resolve the issue. The web service returned an error and that is in HTML format. I resolved the issue on the service server side.
